# Generated by Django 3.1.4 on 2020-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/gallery/'),
        ),
        migrations.AlterField(
            model_name='logofav',
            name='fav',
            field=models.ImageField(blank=True, null=True, upload_to='img/fav/'),
        ),
        migrations.AlterField(
            model_name='logofav',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/logo/'),
        ),
        migrations.AlterField(
            model_name='modifiedimg',
            name='banner_desktop',
            field=models.ImageField(blank=True, null=True, upload_to='img/modifiedImg/desktop/'),
        ),
        migrations.AlterField(
            model_name='modifiedimg',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='img/modifiedImg/mobile/'),
        ),
        migrations.AlterField(
            model_name='modifiedimg',
            name='banner_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='img/modifiedImg/tablet/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/subcategory/'),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/banner/'),
        ),
    ]
